### ISSUE TITLE
Dependency arrows are pointing in the wrong direction

### ISSUE THREAD

**Issue by kobrigo** [vepanimas/intellij-uml-javascript#2]
When you generate a diagram and there is a relation of dependency between two classes or between a class and an interface, the arrow that is being drawn (a dotted line with an open arrow at the end) is pointing in the wrong way. Like if I have class A that is dependent on class B (A has a property of type B). the arrow should be pointing from A to B. Currently it's the other way around. Check [this](https://www.visual-paradigm.com/guide/uml-unified-modeling-language/uml-class-diagram-tutorial/) as a reference.

**Comment by vepanimas** [comment]
Aggregation relationships also point in the wrong direction, a diamond should be on the aggregate side.
